# This workflow will launch at 00:00 every day
name: RDF Tests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  rdf-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install junit2md
        uses: actions-rs/install@v0.1
        with:
          crate: junit2md
          version: 0.1.0
      - name: Update submodules
        run: git submodule init && git submodule update
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-coursier-
      - name: Cache .sbt
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Run RDF tests
        run: sbt "bellman-rdf-tests/test" || true
      - name: Convert Junit XML to Markdown
        run: ~/.cargo/bin/junit2md modules/rdf-tests/target/test-reports/TEST-com.gsk.kg.engine.RdfTests.xml > rdf-test-results.md
      - name: configure git
        run: |
          git config user.name 'Pepegar Bot'
          git config user.email 'pepegar@users.noreply.github.com'
      - name: Create Pull Request
        if: env.NO_CHANGES == null
        id: cpr
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-rdf-report
          delete-branch: true
          title: 'Update RDF Tests report'
          labels: documentation
          body: |
            Update report
      - name: Show Pull Request URL
        if: env.PULL_REQUEST_NUMBER != null
        run: 'echo "Pull-request created: https://github.com/gsk-aiops/bellman/pull/${{ env.PULL_REQUEST_NUMBER }}"'
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
