name: Scala CI

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Label PR
        if: github.event_name == 'pull_request'
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
      - uses: ts-graphviz/setup-graphviz@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: install Jekyll
        run: gem install jekyll -v 4
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-coursier-
      - name: Cache .sbt
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Lint code
        run: sbt ";scalafixAll --check ;scalafmtCheckAll ;scalastyle"
      - name: Run tests
        run: sbt ";clean ;coverage ;+test"
      - name: Build microsite
        run: sbt ";build-microsite"
      - name: Coverage Report
        run: sbt coverageReport
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v1"
        with:
          fail_ci_if_error: true
      - name: Automerge Scala Steward PRs
        if: success() && github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'Scala Steward')
        uses: ridedott/merge-me-action@v2.9.2
        with:
          GITHUB_LOGIN: pepegar
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Dependabot Merge
        if: success()
        uses: ridedott/merge-me-action@v2.9.2
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
